services:
    redis:
        container_name: redis-villa
        image: redis
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning
    backend:
        build: .
        container_name: backend-villa
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./core:/app
        ports:
            - "8080:8080"
        environment:
            - SECRET_KEY=test
            - DEBUG=True
    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            - '5020:80'
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
            - ServerOptions_HostName=smtp4dev
    master:
        image: locustio/locust
        ports:
            - "8089:8089"
        volumes:
            - ./core/locust:/mnt/locust
        command: -f /mnt/locust/locustfile.py --master -H http://backend:8080
    locust_worker:
        image: locustio/locust
        volumes:
            - ./core/locust:/mnt/locust
        command: -f /mnt/locust/locustfile.py --worker --master-host master
    celery_worker:
        build: .
        working_dir: /app
        command: celery -A core worker --loglevel=info
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend
        environment:
            - SECRET_KEY=test
            - DEBUG=True
    celery_beat:
        build: .
        working_dir: /app
        command: celery -A core beat --loglevel=info
        volumes:
            - ./core:/app
        depends_on:
            - redis
            - backend
        environment:
            - SECRET_KEY=test
            - DEBUG=True

volumes:
    smtp4dev-data:
